### ISSUE TITLE
face orientation

### ISSUE THREAD

**Issue by sam199488** [KimDarren/FaceCropper#4]
when we use the camera, your API detects faces only in one orientation

**Comment by KimDarren** [comment]
Would you tell me your situation in detail?

**Comment by sam199488** [comment]
the problem is when I take a picture and use facecropper to get the faces, the ios change the orientation automatically, so when there are faces in a picture, the facecropper doesn't find anything since the image is not in the right orientation. we can solve this by rotating the image to the right orientation using EXIF data

**Comment by KimDarren** [comment]
There's no feature to take a picture in `FaceCropper`.
`FaceCropper` is just an extension for `UIImage` and `CGImage` to crop the faces with `Vision` framework in iOS 11.

But, if you give me some sample codes that incur your issue, I'll check it and reply to you. 
Thanks.
